#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. I keep those commands in ~/config/xprofile because
# that file is run automatically if someone uses a display manager (login
# screen) and so they are needed there. To prevent doubling up commands, I
# source them here with the line below.

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


# source ~/.xprofile
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi


#export XDG_SESSION_TYPE=x11
#export GDK_BACKEND=x11
#export XDG_CURRENT_DESKTOP=Budgie:GNOME
#exec budgie-desktop

#exec startxfce4

source "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile-dwm"  # dwm, window manager specific programs
while :; do
    ssh-agent dwm
done
